export const ITEMS = [
    {
        id:'smallBag',
        name:"Small Bag of $TRTN",
        desc: "A small bag og $TRTN (500-750) used for daily expenses.",
        rarity: "common",
        supply: "50%",
        img: '/images/items/small-bag.png',
        mp4: '/videos/items/small-bag.mp4',
    },
    {
        id:'largeBag',
        name:"Large Bag of $TRTN",
        desc: "A large satchel full of $TRTN (1000-2500) used for traveling.",
        rarity: "rare",
        supply: "50%",
        img: '/images/items/large-bag.png',
        mp4: '/videos/items/large-bag.mp4',
    },
    {
        id:'treasureChest',
        name:"$TRTN Treasure Chest",
        desc: "An ancient treasure chest full of $TRTN (10,000 - 20,000).",
        rarity: "legendary",
        supply: "50%",
        img: '/images/items/treasure-chest.png',
        mp4: '/videos/items/treasure-chest.mp4',
    },
    {
        id:'beastHeart',
        name:"Primordial Beast Heart",
        desc: "The heart of a fallen beast, not seen for thousands of years. It still beats even after the beast has died.",
        rarity: "common",
        supply: "50%",
        img: '/images/items/demon-heart.png',
        mp4: '/videos/items/demon-heart.mp4',
    },
    {
        id:'poseidonCrystal',
        name:"Poseidon Crystals",
        desc: "The Poseidon's crystals were created during the fall of Old Atlantis. It is said, that they are the tears of Poseidon himself, stricken with grief over the death of his wife Amphitrite.",
        rarity: "rare",
        supply: "25%",
        img: '/images/items/poseidon-crystal.png',
        mp4: '/videos/items/poseidon-crystal.mp4',
    },
    {
        id:'spellBook',
        name:"Spell Book",
        desc: "An old spell book created by ancient cult. It is written in a strange language which has not been spoken in thousands of years.",
        rarity: "rare",
        supply: "25%",
        img: '/images/items/spell-book.png',
        mp4: '/videos/items/spell-book.mp4',
    },
    {
        id:'godStone',
        name:"God Stone",
        desc: "The God stones were created during an epic struggle between gods and the primordial horrors who defeated them. When the gods fell, the Horrors dismantled and consumed their bodies only leaving behind their crystallized blood.",
        rarity: "legendary",
        supply: "25%",
        img: '/images/items/god-stone.png',
        mp4: '/videos/items/god-stone.mp4',
    },
    {
        id:'godSkinSpellBook',
        name:"Godskin Spell Book",
        desc: "An ancient spell book created from the skin of a fallen god. It's appearance is corrupted by the dark magic that lies inside.",
        rarity: "legendary",
        supply: "25%",
        img: '/images/items/god-skin-spell-book.png',
        mp4: '/videos/items/god-skin-spell-book.mp4',
    },

];
