module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        yellow: "#FEFF05",
        green: "#01A47B",
        "green-light": "#05D5A1",
        "body": "#1b527b",
      },
      fontFamily: {
        scratchy: ['Scratchy', 'serif'],
        jangkuy: ['Jangkuy', 'serif'],
      },
    },
    screens: {
      sm: '480px',
      md: '768px',
      lg: '976px',
      xl: '1100px',
    },
    fontSize: {
      'xs': '.75rem',
      'sm': '.875rem',
      'tiny': '.875rem',
      'base': '0.90rem',
      'lg': '1.1rem',
      'xl': '1.2rem',
      '2xl': '1.45rem',
      '3xl': '1.8rem',
      '4xl': '2.2rem',
      '5xl': '3rem',
      '6xl': '4rem',
      '7xl': '5rem',
    }
  },
  plugins: [require("daisyui"), require('tailwindcss-textshadow')],
  daisyui: {
    themes: [
      {
        TRITON: {
          primary: "#541FF3",
          "primary-focus": "#541FF3",
          "primary-content": "#181830",
          secondary: "#fd7cf6",
          "secondary-focus": "#fd7cf6",
          "secondary-content": "#ffffff",
          accent: "#05D5A1",
          "accent-focus": "#09C596",
          "accent-content": "#ffffff",
          neutral: "#181830",
          "neutral-focus": "#111122",
          "neutral-content": "#ffffff",
          "base-100": "transparent",
          "base-200": "#ffffff",
          "base-300": "#A134FE",
          "base-content": "#fff",
          info: "#2094f3",
          success: "#009485",
          warning: "#ff9900",
          error: "#ff5724",
          "--border-color": "var(--b3)",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.9rem",
          "--animation-btn": "0.25s",
          "--animation-input": ".2s",
          "--btn-text-case": "uppercase",
          "--btn-focus-scale": "0.95",
          "--navbar-padding": ".5rem",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.5rem",
        },
      },
    ],
  },
};
